### ISSUE TITLE
1.18 error/problem

### ISSUE THREAD

**Issue by Tuurkevg** [cervinakuy/JoinEventsPro#10]
[12:03:26 ERROR]: Cannot load configuration from stream
org.bukkit.configuration.InvalidConfigurationException: while parsing a block collection
in 'string', line 29, column 7:
- 'Do you need help? Make a tick ...
^
expected <block end>, but found '<scalar>'
in 'string', line 38, column 51:
... ou get a head of the person you've killed.
^

at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:59) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:217) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
at me.cervinakuy.joineventspro.util.Resource.copyDefaults(Resource.java:71) ~[JoinEventsPro.jar:?]
at me.cervinakuy.joineventspro.util.Resources.load(Resources.java:42) ~[JoinEventsPro.jar:?]
at me.cervinakuy.joineventspro.util.Resources.reload(Resources.java:50) ~[JoinEventsPro.jar:?]
at me.cervinakuy.joineventspro.command.MainCommand.onCommand(MainCommand.java:62) ~[JoinEventsPro.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:876) ~[paper-1.18.jar:git-Paper-39]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2201) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2012) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1993) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.jar:git-Paper-39]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.jar:git-Paper-39]
at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.jar:git-Paper-39]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.jar:git-Paper-39]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.jar:git-Paper-39]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1362) ~[paper-1.18.jar:git-Paper-39]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268) ~[paper-1.18.jar:git-Paper-39]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.jar:git-Paper-39]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block collection
in 'string', line 29, column 7:
- 'Do you need help? Make a tick ...
^
expected <block end>, but found '<scalar>'
in 'string', line 38, column 51:
... ou get a head of the person you've killed.
^

at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockSequenceEntry.produce(ParserImpl.java:555) ~[snakeyaml-1.28.jar:?]
at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:165) ~[snakeyaml-1.28.jar:?]
at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:59) ~[snakeyaml-1.28.jar:?]
at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:45) ~[snakeyaml-1.28.jar:?]
at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:140) ~[snakeyaml-1.28.jar:?]
at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:119) ~[snakeyaml-1.28.jar:?]
at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:221) ~[snakeyaml-1.28.jar:?]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:191) ~[snakeyaml-1.28.jar:?]
at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:251) ~[snakeyaml-1.28.jar:?]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:193) ~[snakeyaml-1.28.jar:?]
at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:313) ~[snakeyaml-1.28.jar:?]
at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:304) ~[snakeyaml-1.28.jar:?]
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:288) ~[snakeyaml-1.28.jar:?]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:195) ~[snakeyaml-1.28.jar:?]
at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:313) ~[snakeyaml-1.28.jar:?]
at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:304) ~[snakeyaml-1.28.jar:?]
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:288) ~[snakeyaml-1.28.jar:?]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:195) ~[snakeyaml-1.28.jar:?]
at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:313) ~[snakeyaml-1.28.jar:?]
at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:304) ~[snakeyaml-1.28.jar:?]
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:288) ~[snakeyaml-1.28.jar:?]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:195) ~[snakeyaml-1.28.jar:?]
at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:115) ~[snakeyaml-1.28.jar:?]
at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:146) ~[snakeyaml-1.28.jar:?]
at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151) ~[snakeyaml-1.28.jar:?]
at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490) ~[snakeyaml-1.28.jar:?]
at org.yaml.snakeyaml.Yaml.load(Yaml.java:416) ~[snakeyaml-1.28.jar:?]
at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
... 28 more

**Comment by cervinakuy** [comment]
According to the stacktrace, it looks like you made a syntax error. I would verify your config.yml using [this format checker](https://yaml.helpch.at/) before reloading / restarting with a new config.

**Comment by Tuurkevg** [comment]
https://yaml.helpch.at/#yaml=IyBEb2N1bWVudGF0aW9uIGZvciB1c2luZyBjb21tYW5kcyBpbiBjb25maWd1cmF0aW9uIGZpbGVzIGNhbiBiZSBmb3VuZCBoZXJlOgojIGdpdGh1Yi5jb20vY2VydmluYWt1eS9LaXRQdlAvd2lraS9UeXBpY2FsLUZvcm1hdHMKCkxlYXZlOgogIE1lc3NhZ2U6CiAgICBNZXNzYWdlOiAnJjdbJmMmbFNlcnZlciY3XSAmYiVwbGF5ZXIlICY3bGVmdCB0aGUgc2VydmVyJwogICAgRW5hYmxlZDogZmFsc2UKICBTb3VuZDoKICAgIFNvdW5kOiBOT1RFX0JBU1MKICAgIFBpdGNoOiAxCiAgICBFbmFibGVkOiBmYWxzZQogIENvbW1hbmRzOiBbXQpTZXJ2ZXI6CiAgTU9URDoKICAgIE9wdGlvbnM6CiAgICAgIE1haW50ZW5hbmNlOiBmYWxzZQogICAgICBFbmFibGVkOiB0cnVlCiAgICBMaXN0OgogICAgICBSYW5kb21CbHVlOgogICAgICAgIExpbmUtMTogJyZiJmxNaW5lY3JhZnQgTmV0d29yayAmM05vdyB3aXRoIEpvaW5FdmVudHNQcm8hJwogICAgICAgIExpbmUtMjogJyYzVGhpcyBpcyBhIGN1c3RvbWl6YWJsZSBzZWNvbmQgbGluZSBvZiB0aGUgTU9URC4nCiAgICAgIFJhbmRvbUdyZWVuOgogICAgICAgIExpbmUtMTogJyYyJmxNaW5lY3JhZnQgTmV0d29yayAmYU5vdyB3aXRoIEpvaW5FdmVudHNQcm8hJwogICAgICAgIExpbmUtMjogJyZhVGhpcyBpcyBhIGN1c3RvbWl6YWJsZSBzZWNvbmQgbGluZSBvZiB0aGUgTU9URC4nCiAgICAgIFJhbmRvbVllbGxvdzoKICAgICAgICBMaW5lLTE6ICcmZSZsV2UgQXJlIHVuZGVyZ29pbmcgbWFpbnRlbmFuY2UgIScKICAgICAgICBMaW5lLTI6ICcmNkNoZWNrIG91ciBEaXNjb3JkJwogICAgICBNYWludGVuYW5jZToKICAgICAgICBMaW5lLTE6ICcmYyZsV2UgYXJlIHdvcmtpbmcgb24gdGhlIHNlcnZlciEnCiAgICAgICAgTGluZS0yOiAnJkNoZWNrIG91ciBkaXNjb3JkIGZvciBtb3JlIGluZm9ybWF0aW9uIScKICBNZXNzYWdlczoKICAgIEZ1bGw6ICcmN1smYiZsU2VydmVyJjddICZjVGhlIHNlcnZlciBpcyBjdXJyZW50bHkgZnVsbCwgcGxlYXNlIGNoZWNrIGJhY2sgbGF0ZXIuJwogICAgTWFpbnRlbmFuY2U6ICcmN1smYiZsU2VydmVyJjddICZjVGhlIHNlcnZlciBpcyBjdXJyZW50bHkgdW5kZXJnb2luZyBNYWludGVuYW5jZSwKICAgICAgcGxlYXNlIGNoZWNrIGJhY2sgbGF0ZXIuJwogIFBsYXllcnM6CiAgICBVbmxpbWl0ZWQ6IHRydWUKICAgIE1heDogMTAwCg==
here you go.

**Comment by Tuurkevg** [comment]
I reset my full config file but still get the same error... Only on 1.18 I get this error. So it is not my syntax in the config.
