### ISSUE TITLE
"Could not pass event PlayerInteractEvent to JoinEventsPro"

### ISSUE THREAD

**Issue by Cretezy** [cervinakuy/JoinEventsPro#8]
```
[Sun, 21. Mar 2021 06:04:50 CET ERROR] Could not pass event PlayerInteractEvent to JoinEventsPro v4.2
```

Getting this error spammed in my console, any information to why?

**Comment by cervinakuy** [comment]
Can you include the full error?

**Comment by Cretezy** [comment]
Sorry I can't reproduce it anymore.

I did find the cause though. My config for first join looks like:

```
  Items:
    Beef:
      Name: ''
      Material: COOKED_BEEF
      Permission: jep.firstjoin.items
      Slot: 1
      Amount: 8
      Override: false
    Enabled: true
```

And since name is `''`, it tries to compare it in the PlayerInteractEvent, and fails somehow. If I can get the full stacktrace again, I'll post it here.

**Comment by Cretezy** [comment]
```
[18:00:02 ERROR]: Could not pass event PlayerInteractEvent to JoinEventsPro v4.2
java.lang.IllegalArgumentException: Cannot match a material with null or empty material name
        at org.apache.commons.lang.Validate.notEmpty(Validate.java:321) ~[patched_1.16.5.jar:git-Paper-565]
        at com.planetgallium.kitpvp.XMaterial.matchXMaterial(XMaterial.java:1495) ~[?:?]
        at me.cervinakuy.joineventspro.listener.JoinItems.onInteract(JoinItems.java:98) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor76.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-565]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-565]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-565]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-565]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:531) ~[patched_1.16.5.jar:git-Paper-565]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:498) ~[patched_1.16.5.jar:git-Paper-565]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1698) ~[patched_1.16.5.jar:git-Paper-565]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:31) ~[patched_1.16.5.jar:git-Paper-565]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9) ~[patched_1.16.5.jar:git-Paper-565]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-565]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-565]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-565]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-565]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-565]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1252) ~[patched_1.16.5.jar:git-Paper-565]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1245) ~[patched_1.16.5.jar:git-Paper-565]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-565]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1319) ~[patched_1.16.5.jar:git-Paper-565]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1116) ~[patched_1.16.5.jar:git-Paper-565]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-565]
```

**Comment by cervinakuy** [comment]
@Cretezy Sorry for the wait. I think I found the cause. Do you mind trying [this jar](https://www.dropbox.com/s/unsek24r7x3v3jc/JoinEventsPro.jar?dl=0) and letting me know if it fixes the error for you?

**Comment by cervinakuy** [comment]
Fixed as per @BeepoWuff's PR. Thanks.
